# Generated by Django 5.2 on 2026-03-04 03:12

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название слайда', max_length=255, verbose_name='Название')),
                ('alt_text', models.CharField(blank=True, help_text='Альтернативный текст для изображения', max_length=255, verbose_name='Alt-текст')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать слайд на сайте', verbose_name='Активен')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', filer.fields.image.FilerImageField(help_text='Загрузите изображение через файловый менеджер', on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['order'],
            },
        ),
    ]
